version: '3.7'

services:
  warehouse:
    image: lamoda-test-image
    volumes:
      - .:/lamoda-test
    ports:
      - 4000:4000
    depends_on:
      - postgres
    networks:
      - learning


  postgres:
    restart: always
    container_name: postgres
    image: postgres:15-alpine
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    networks:
      - learning

networks:
  learning:
    driver: bridge