version: '3.7'

services:
  warehouse:
    image: lamoda-test-image
    volumes:
      - .:/lamoda-test:cached
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    restart: always
    container_name: warehouse-db
    image: postgres:15-alpine
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5433